name: "build"

on:
  push:
  pull_request:
    branches:
      - latest

jobs:
  simple-build:
    name: "Build and Test"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ghidra: ["10.3"]
        include:
          - ghidra: "10.3"
            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3_build/ghidra_10.3_PUBLIC_20230510.zip"
            ghidra-sha256: "4e990af9b22be562769bb6ce5d4d609fbb45455a7a2f756167b8cdcdb75887fc"
            ghidra-filename: "ghidra_10.3_PUBLIC_20230510.zip"
            ghidra-folder: "ghidra_10.3_PUBLIC"
          - ghidra: "10.3.1"
            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.1_build/ghidra_10.3.1_PUBLIC_20230614.zip"
            ghidra-sha256: "0413b679436039cc136b950a6d8c24e80ce79da0a0a48993dfacee671b1c7974"
            ghidra-filename: "ghidra_10.3.1_PUBLIC_20230614.zip"
            ghidra-folder: "ghidra_10.3.1_PUBLIC"
          - ghidra: "10.3.2"
            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.2_build/ghidra_10.3.2_PUBLIC_20230711.zip"
            ghidra-sha256: "a658677a87d0be12ab65bd7962f471875b81a2dd2ea35d69cc3201555ca1bd6f"
            ghidra-filename: " ghidra_10.3.2_PUBLIC_20230711.zip"
            ghidra-folder: "ghidra_10.3.2_PUBLIC"

    env:
      GHIDRA_INSTALL_DIR: /home/runner/ghidra/${{ matrix.ghidra-folder }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ghidra
        uses: actions/cache@v2
        id: cache-ghidra
        with:
          path: ~/ghidra
          key: ${{ runner.os }}-${{ matrix.ghidra }}
      - name: Get Ghidra
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          wget -q ${{ matrix.ghidra-url }}
          echo "${{ matrix.ghidra-sha256 }} ${{ matrix.ghidra-filename }}" | sha256sum -c
          unzip ${{ matrix.ghidra-filename }} -d ~/ghidra
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Set Up SDK Environment
        run: |
          curl -s "https://get.sdkman.io?rcupdate=false" | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 7.4
          sdk use gradle 7.4
          sdk default gradle 7.4
      - name: Run Unit Tests
        run: |
          echo "skipping gradle test due to inconsistencies in reliability"
      - name: Build and Install
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          gradle buildExtension
          rm -rf $GHIDRA_INSTALL_DIR/Ghidra/Extensions/ruby-dragon
          unzip dist/$(ls dist) -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
          mkdir ~/projects
      - name: JRubyBasics Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -preScript JRubyBasicsScriptRb.rb -deleteProject | grep -v "^\(INFO\)\|\(WARN\)\|\(    \)" > actual.txt
          awk '/^=begin$/{flag=1;next}/^=end$/{flag=0}flag' ghidra_scripts/JRubyBasicsScriptRb.rb > expected.txt
          diff actual.txt expected.txt
          rm actual.txt expected.txt
      - name: Ghidra Basics Ruby Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptRb.rb HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Ghidra Basics Kotlin Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptKts.kts HeadlessTest -deleteProject | sed -n "s/^INFO  GhidraBasicsScriptKts.kts> \(.*\) (GhidraScript).*$/\1/p" > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Ghidra Basics Groovy Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptGroovy.groovy HeadlessTest -deleteProject | sed -n "s/^INFO  GhidraBasicsScriptGroovy.groovy> \(.*\) (GhidraScript).*$/\1/p" > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Ghidra Basics Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptClj.clj HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Save Strings Ruby Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptRb.rb TestStringsRuby.txt -deleteProject
          grep "Hello Ghidra!" TestStringsRuby.txt
          rm TestStringsRuby.txt
      - name: Save Strings Kotlin Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptKts.kts TestStringsKotlin.txt -deleteProject
          grep "Hello Ghidra!" TestStringsKotlin.txt
          rm TestStringsKotlin.txt
      - name: Save Strings Groovy Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptGroovy.groovy TestStringsGroovy.txt -deleteProject
          grep "Hello Ghidra!" TestStringsGroovy.txt
          rm TestStringsGroovy.txt
      - name: Save Strings Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptClj.clj TestStringsClojure.txt  -deleteProject
          grep "Hello Ghidra!" TestStringsClojure.txt
          rm TestStringsClojure.txt
