name: "build"

on:
  push:
  pull_request:
    branches:
      - latest

jobs:
  simple-build:
    name: "Build and Test"
    runs-on: "ubuntu-latest"
    env:
      GHIDRA_INSTALL_DIR: '/home/runner/ghidra/ghidra_10.0.2_PUBLIC'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ghidra
        uses: actions/cache@v2
        id: cache-ghidra
        with:
          path: ~/ghidra
          key: ${{ runner.os }}-10-0-2-${{ hashFiles('lib/*.jar') }}
      - name: Get Ghidra
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.2_build/ghidra_10.0.2_PUBLIC_20210804.zip
          echo "5534521ccb958b5cde04fc5c51bfa2918d475af49e94d372fa7c117cc9fe804b ghidra_10.0.2_PUBLIC_20210804.zip" | sha256sum -c
          unzip ghidra_10.0.2_PUBLIC_20210804.zip -d ~/ghidra
      - name: Run Unit Tests
        run: |
          gradle test
      - name: Build and Install
        run: |
          gradle buildExtension
          unzip dist/$(ls dist) -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
      - name: JRubyBasics Script
        run: |
          mkdir ~/projects
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -preScript ./ghidra_scripts/JRubyBasicsScriptRb.rb -deleteProject | grep -v "^\(INFO\)\|\(WARN\)\|\(    \)" > actual.txt
          awk '/^=begin$/{flag=1;next}/^=end$/{flag=0}flag' ghidra_scripts/JRubyBasicsScriptRb.rb > expected.txt
          diff actual.txt expected.txt
          rm actual.txt expected.txt
      - name: Ghidra Basics Ruby Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript ./ghidra_scripts/GhidraBasicsScriptRb.rb HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
          awk '/^=begin$/{flag=1;next}/^=end$/{flag=0}flag' ghidra_scripts/GhidraBasicsScriptRb.rb > expected.txt
          diff actual.txt expected.txt
          rm actual.txt expected.txt
      - name: Ghidra Basics Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript ./ghidra_scripts/GhidraBasicsScriptClj.clj HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
           awk '/; src\/test\/resources\/bin\/HelloGhidra.exe/{flag=1;next} flag' ghidra_scripts/GhidraBasicsScriptClj.clj | cut -c 2- > expected.txt
          diff actual.txt expected.txt
          rm actual.txt expected.txt
      - name: Save Strings Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript ./ghidra_scripts/SaveStringsScriptClj.clj TestStrings.txt -deleteProject
          grep "Hello Ghidra!" TestStrings.txt
          rm TestStrings.txt
