name: "build"

on:
  push:
  pull_request:
    branches:
      - latest

jobs:
  simple-build:
    name: "Build and Test"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
#        ghidra: ["10.0.4", "10.1.2", "10.1.4"]
        ghidra: ["10.1.2", "10.1.4"]
        include:
#          - ghidra: "10.0.4"
#            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0.4_build/ghidra_10.0.4_PUBLIC_20210928.zip"
#            ghidra-sha256: "1ce9bdf2d7f6bdfe5dccd06da828af31bc74acfd800f71ade021d5211e820d5e"
#            ghidra-filename: "ghidra_10.0.4_PUBLIC_20210928.zip"
#            ghidra-folder: "ghidra_10.0.4_PUBLIC"
          - ghidra: "10.1.2"
            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.2_build/ghidra_10.1.2_PUBLIC_20220125.zip"
            ghidra-sha256: "ac96fbdde7f754e0eb9ed51db020e77208cdb12cf58c08657a2ab87cb2694940"
            ghidra-filename: "ghidra_10.1.2_PUBLIC_20220125.zip"
            ghidra-folder: "ghidra_10.1.2_PUBLIC"
          - ghidra: "10.1.4"
            ghidra-url: "https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.1.4_build/ghidra_10.1.4_PUBLIC_20220519.zip"
            ghidra-sha256: "91556c77c7b00f376ca101a6026c0d079efbf24a35b09daaf80bda897318c1f1"
            ghidra-filename: "ghidra_10.1.4_PUBLIC_20220519.zip"
            ghidra-folder: "ghidra_10.1.4_PUBLIC"

    env:
      GHIDRA_INSTALL_DIR: /home/runner/ghidra/${{ matrix.ghidra-folder }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ghidra
        uses: actions/cache@v2
        id: cache-ghidra
        with:
          path: ~/ghidra
          key: ${{ runner.os }}-${{ matrix.ghidra }}
      - name: Get Ghidra
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          wget -q ${{ matrix.ghidra-url }}
          echo "${{ matrix.ghidra-sha256 }} ${{ matrix.ghidra-filename }}" | sha256sum -c
          unzip ${{ matrix.ghidra-filename }} -d ~/ghidra
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Set Up SDK Environment
        run: |
          curl -s "https://get.sdkman.io?rcupdate=false" | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 6.9
          sdk use gradle 6.9
          sdk default gradle 6.9
      - name: Run Unit Tests
        run: |
          gradle test
      - name: Build and Install
        run: |
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          gradle buildExtension
          rm -rf $GHIDRA_INSTALL_DIR/Ghidra/Extensions/ruby-dragon
          unzip dist/$(ls dist) -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
          mkdir ~/projects
      - name: JRubyBasics Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -preScript JRubyBasicsScriptRb.rb -deleteProject | grep -v "^\(INFO\)\|\(WARN\)\|\(    \)" > actual.txt
          awk '/^=begin$/{flag=1;next}/^=end$/{flag=0}flag' ghidra_scripts/JRubyBasicsScriptRb.rb > expected.txt
          diff actual.txt expected.txt
          rm actual.txt expected.txt
      - name: Ghidra Basics Ruby Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptRb.rb HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Ghidra Basics Kotlin Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptKts.kts HeadlessTest -deleteProject | sed -n "s/^INFO  GhidraBasicsScriptKts.kts> \(.*\) (GhidraScript).*$/\1/p" > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Ghidra Basics Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript GhidraBasicsScriptClj.clj HeadlessTest -deleteProject | awk '/^INFO  SCRIPT:/{flag=1;next}/^INFO  /{flag=0}flag' > actual.txt
          diff actual.txt src/test/resources/expected/GhidraBasicsScript.txt
          rm actual.txt
      - name: Save Strings Ruby Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptRb.rb TestStringsRuby.txt -deleteProject
          grep "Hello Ghidra!" TestStringsRuby.txt
          rm TestStringsRuby.txt
      - name: Save Strings Kotlin Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptKts.kts TestStringsKotlin.txt -deleteProject
          grep "Hello Ghidra!" TestStringsKotlin.txt
          rm TestStringsKotlin.txt
      - name: Save Strings Clojure Script
        run: |
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -import ./src/test/resources/bin/HelloGhidra.exe -postScript SaveStringsScriptClj.clj TestStringsClojure.txt  -deleteProject
          grep "Hello Ghidra!" TestStringsClojure.txt
          rm TestStringsClojure.txt
