name: "build"

on:
  push:
  pull_request:
    branches:
      - latest

jobs:
  simple-build:
    name: "build extension"
    runs-on: "ubuntu-latest"
    env:
      GHIDRA_INSTALL_DIR: '/home/runner/ghidra/ghidra_10.0_PUBLIC'
    steps:
      - uses: actions/checkout@v2
      - name: Cache Ghidra
        uses: actions/cache@v2
        id: cache-ghidra
        with:
          path: ~/ghidra
          key: ${{ runner.os }}-${{ hashFiles('lib/*.jar') }}
      - name: Get Ghidra
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.0_build/ghidra_10.0_PUBLIC_20210621.zip
          unzip ghidra_10.0_PUBLIC_20210621.zip -d ~/ghidra
      - name: Run Unit Tests
        run: |
          gradle test
      - name: Build and Install
        run: |
          gradle buildExtension
          unzip dist/$(ls dist) -d $GHIDRA_INSTALL_DIR/Ghidra/Extensions
      - name: Run Headless Tests
        run: |
          mkdir ~/projects
          $GHIDRA_INSTALL_DIR/support/analyzeHeadless ~/projects/ RubyDragonTest -preScript ./ghidra_scripts/JRubyBasicsScriptRb.rb -deleteProject | grep -v "^\(INFO\)\|\(WARN\)\|\(    \)" > actual.txt
          awk '/^=begin$/{flag=1;next}/^=end$/{flag=0}flag' ghidra_scripts/JRubyBasicsScriptRb.rb > expected.txt
          diff actual.txt expected.txt